#!/usr/bin/env python3
import AWH_font_styl
import scanning_defs as net_scan
import port_scan_defs as port_scan_op
AWH_font_styl.fontStyl()
print("AWH giving you many option to sccane , sniffe , descover your network") #chang it another
print("\n------------------------------------------------")
def queet():
    quit()
def start_all(): #main menu (M)
    print("[+] *  Back for previous page\n[+] M  For main menu\n[+] Q  For quit the tool ")
    print("------------------------------------------------")
    print("1-Get started\n2-Help\n3-About")  # desine it
    intfc=input("enter number : ")
    if intfc=="1":#get start
        print("\n------------------------------------------------")
        def get_started():
            print("1-scanning\n2-sniffing\n*-back")
            num=input("enter numer : ")
            if num=="1":#scanning
                print("\n------------------------------------------------")
                def scanning():
                    print("1-THIS DEVICE\n2-OTHER DEVICE\n*-back")
                    scan=input("enter number : ")
                    if scan == "1":
                        print("\n------------------------------------------------")
                        print("1-NETWORK SCANNING\n2-PORT SCANNING\n3-VULNERABILITY SCANNING\n*-back")
                        scan1=input("enter number : ")
                        if scan1=="1":
                            def net_scane():
                                print("")
                                #scanning.get_mac
                            net_scane()
                        elif scan1=="2":
                            def port_scan():
                                print("")
                            port_scan()
                        elif scan1=="2":
                            def vul_scan():
                                print("")
                            vul_scan()
                        elif scan1=="*":
                            print("\n------------------------------------------------")
                            scanning()
                        elif scan1 == "m" or num == "M":
                            start_all()
                        elif scan1 == "q" or num == "Q":
                            queet()
                        else:
                            print("\n*********************************************")
                            print("\n******* Wrong value ********")
                            print("\n*********************************************")
                    elif scan =="2":#other device
                        def other_device():
                            print("\n------------------------------------------------")
                            print("1-Network scanning\n2-Port scanning\n*-back")
                            scan2=input("enter number : ")
                            if scan2 == "1": #network scan
                                def net_scan():
                                    net_scan.all()
                                net_scan()
                            elif scan2 == "2": #port scan
                                port_scan_op.all()
                            elif scan2=="*":
                                print("\n------------------------------------------------")
                                get_started()

                            elif scan2 == "m" or num == "M":
                                start_all()
                            elif scan2 == "q" or num == "Q":
                                queet()
                            else:
                                print("\n*********************************************")
                                print("\n******* Wrong value ********")
                                print("\n*********************************************")
                        other_device()
                    elif scan =="*": #back for scanning
                        print("\n------------------------------------------------")
                        scanning()
                    elif scan == "m" or num == "M":
                        start_all()
                    elif scan == "q" or num == "Q":
                        queet()
                    else:
                        print("\n*********************************************")
                        print("\n******* Wrong value ********")
                        print("\n*********************************************")
                        scanning()
                scanning()
            elif num=="2":#sniffing
                print("\n------------------------------------------------")
                def sniffing():
                    print("1-all\n2-HTTP\n3-TCP\n4-UDP\n5-IP\n*-back")
                    sniff=input("enter number : ")
                    if sniff == "1":
                        print("")
                    elif sniff=="2":
                        def http_sniff():
                            print("")
                        http_sniff()
                    elif sniff=="3":
                        def tcp_sniff():
                            print("")
                        tcp_sniff()
                    elif sniff=="4":
                        def udp_sniff():
                            print("")
                        udp_sniff()
                    elif sniff=="5":
                        def ip_sniff():
                            print("")
                        ip_sniff()
                    elif sniff == "*":
                        print("\n------------------------------------------------")
                        get_started()
                    elif sniff == "m" or num == "M":
                        start_all()
                    elif sniff == "q" or num == "Q":
                        queet()

                    else:
                        print("\n*********************************************")
                        print("\n******* Wrong value ********")
                        print("\n*********************************************")
                        sniffing()
                sniffing()                                   #future working make a discovering
            elif num == "*":#back for start all
                print("\n------------------------------------------------")
                start_all()
            elif num == "m" or num == "M":
                start_all()
            elif num == "q" or num == "Q":
                queet()
            else:
                print("\n*********************************************")
                print("\n******* Wrong value ********")
                print("\n*********************************************")
                get_started()
        get_started()
    elif intfc=="2":#help
        print("\n------------------------------------------------")
        def help():
            print("1-How to scan the Network\n2-How to sniff the Network\n3-How to discover the Network\n*-Back")
            num = input("enter numer : ")

            if num == "1" or num == "2" or num == "3" :
                if num=="1":#How to scan the Network
                    print("\n------------------------------------------------")
                    print("")
                elif num=="2":#How to sniff the Network
                    print("\n------------------------------------------------")
                    print("")
                elif num=="3":#How to discover the Network
                    print("\n------------------------------------------------")
                    print("")
                elif num == "m" or num == "M":
                    start_all()
                elif num == "q" or num == "Q":
                    quit
            elif num == "*":
                    start_all()
            elif num == "m" or num == "M":
                start_all()
            elif num == "q" or num == "Q":
                queet()
            else:
                print("\n*********************************************")
                print("\n******* Wrong value ********")
                print("\n*********************************************")
                help()
        help()
    elif intfc=="3":#about
        print("\n------------------------------------------------")
        def about():
            #print("\n------------------------------------------------")
            print("This tool is specialized in a number of tasks that may benefit you in SCAN , SNIFF or DISCOVER your private network or in your Penetration testing. ")
            print("created by:\n.Ahmad Almasharqa \n.Waseem Mohammad  \n.Hanin Hashaikah ")
            back=input("\npress * to back to main menu\n")

            if back == "*":
                start_all()
            elif back == "m" or back == "M":
                start_all()
            elif back == "q" or back == "Q":
                queet()
            else:
                print("\n*********************************************")
                print("\n******* Wrong value ********")
                print("\n*********************************************")
                about()
        about()
    elif intfc == "q" or intfc == "Q":
        queet()
    else:
        print("\n*********************************************")
        print("\n******* Wrong value ********")
        print("\n*********************************************")
    #   subprocess.call("figlet -f big 'WISE -- AWH'", shell=True) change the font to small and disine it
        start_all()
start_all()
