#!/usr/bin/env python3
import AWH_font_styl
import defs
AWH_font_styl.fontStyl()
print("AWH giving you many option to sccane , sniffe , descover your network") #chang it another

ss = ["q","Q","m","M"]
o1 = defs.intro()
o2 = defs.scanning()
o3 = defs.info()
oo = [o1.intfc,o1.num,o2.scan,o2.por,o2.por1,o3.help,o3.about]
def MQ(i):
    if i == "m" or i == "M":  # main menu (M)
        o1.start_all()
    elif i == "q" or i == "Q":  # quit (Q)
        # print(oo)
        # oo.append(["", "", "", "", ""])
        print(oo)
        #oo.append([" ", " ", " ", " ", " ", " ",]) # o1.intfc,o1.num,o2.scan,o2.por,o3.help,o3.about
        exit(start)
def start():
    def po():
        o2.por_scan()
        if o2.por != "": # (PORT SCANNING) 1- all ports 2- chose ports range 3- top 50 famous port
            if o2.por == "1": # 1- all ports
                print("\n------------------------------------------------")
                if o2.por1 not in ss:
                    o2.target_host = o2.por1
                    o2.por_scan()  #(target_host=target_host, start_port=1, end_port=65535)
                elif o2.por1 in ss:
                    MQ(o2.por1)
                else:
                    print("\n*********************************************")
                    print("\n******* Wrong value 6 ********")
                    print("\n*********************************************")
                    o2.por = "1"
                    po()
            elif o2.por == "2": # 2- chose ports range
                print("\n------------------------------------------------")
                target_host = input("Enter the target host: ")
                if target_host not in ss:
                    start_port = int(input("Enter the start port number: "))
                    end_port = int(input("Enter the end port number: "))
                    o2.target_host = target_host
                    o2.start_port = start_port
                    o2.end_port = end_port
                    o2.por_scan()
                elif target_host in ss:
                    MQ(target_host)
                else:
                    print("\n*********************************************")
                    print("\n******* Wrong value 7 ********")
                    print("\n*********************************************")
                    o2.por = "2"
                    start()
            elif o2.por == "3":
                print((""))
            elif o2.por == "*":  # *-back
                o2.por = " "
                start()
            elif o2.por in ss:
                MQ(o2.por)
            else:
                print("\n*********************************************")
                print("\n******* Wrong value 8 ********")
                print("\n*********************************************")
                o1.num = "1"
                start()

    def sc():
        o2.scanning()
        if o2.scan != "": # (scanning) 1-NETWORK SCANNING 2-PORT SCANNING 3-VULNERABILITY SCANNING *-back
            if o2.scan == "1": # 1-NETWORK SCANNING
                #o2.scan = ""
                o2.net_scan()
                sc()
            elif o2.scan == "2": # 2-PORT SCANNING
                po()
            elif o2.scan == "3": # 3-VULNERABILITY SCANNING
                print("")
            elif o2.scan == "*":  # *-back
                o2.scan = ""
                gs()
            elif o2.scan in ss:
                MQ(o2.scan)
            else:
                print("\n*********************************************")
                print("\n******* Wrong value 5 ********")
                print("\n*********************************************")
                sc()

    def gs():
        print("gs")
        o1.get_started()
        if o1.num != "": # (get start) 1-scanning 2-sniffing *-back
            if o1.num == "1": # 1-scanning
                sc() # 1-NETWORK SCANNING 2-PORT SCANNING 3-VULNERABILITY SCANNING *-back
            elif o1.num == "2": # 2-sniffing
                defs.sniffing()
            elif o1.num == "*" : # *-back + main menu (M) (get started)
                m()
            elif o1.num in ss:
                MQ(o1.num)
            else:
                print("\n*********************************************")
                print("\n******* Wrong value 2 ********")
                print("\n*********************************************")
                gs()
    def h():
        o3.help()
        if o3.hlp != "": # (help) 1-How to scan the Network 2-How to sniff the Network *-Back
            if o3.hlp == "1":  # How to scan the Network
                print("\n------------------------------------------------")
                print("scan")
            elif o3.hlp == "2":  # How to sniff the Network
                print("\n------------------------------------------------")
                print("sniff")
            elif o3.hlp == "*":  # *-back + main menu (M) (get started)
                o3.hlp = "" # o1.intfc,o1.num,o2.scan,o2.por,o3.help,o3.about
                o1.intfc = ""
                m()
            elif o3.hlp in ss:
                MQ(o3.hlp)
            else:
                print("\n*********************************************")
                print("\n******* Wrong value 3 ********")
                print("\n*********************************************")
                h()
    def ab():
        o3.about()
        if o3.abot != "": # 3 - about
            if o3.abot == "*":  # *-back + main menu (M) (get started)
                o3.abot = ""
                m()
            elif o3.abot in ss:
                MQ(o3.abot)
            else:
                print("\n*********************************************")
                print("\n******* Wrong value 4 ********")
                print("\n*********************************************")
                ab()
    def m():
        o1.start_all()
        if o1.intfc != "": # main menu (M)
            if o1.intfc =="1": # 1-get start
                gs() # 1-scanning 2-sniffing *-back
            elif o1.intfc == "2": # 2-help
                h()
            elif o1.intfc == "3": # 3-about
                ab()
            elif o1.intfc == "q" or o1.intfc == "Q": # quit (qut)
                MQ("q")
            else:
                print("\n*********************************************")
                print("\n******* Wrong value 1 ********")
                print("\n*********************************************")
                o1.intfc = ""
                start()
    m()
start()
